export const RESET = 'RESET';
export const START_DOWNLOAD = 'START_DOWNLOAD';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const COMPLETE_DOWNLOAD = 'COMPLETE_DOWNLOAD';
export const DOWNLOAD_ERROR = 'DOWNLOAD_ERROR';
